### ISSUE TITLE
crontab设置log.txt需写全路径

### ISSUE THREAD

**Issue by Luobogao** [metowolf/BilibiliHelper#1]
安装的第4：`3 0 * * * php [path_to_yourfile]/index.php > log.txt`
我认为应为`3 0 * * * php [path_to_yourfile]/index.php > [path_to_yourfile]/log.txt`
或者`3 0 * * * cd [path_to_yourfile] && php index.php > log.txt`
因为用crontab运行php时应为全路径，麻烦检查一下。
（还有要自动开宝箱不是应该设为5分钟运行一次的吗OvO？

**Comment by metowolf** [comment]
对的，log 文件也需要填写绝对路径
原先 5 分钟运行一次是心跳包的逻辑，而整合后，我设计了队列锁，因此每天仅需运行一次，到 23:59 会自动结束脚本
