### ISSUE TITLE
readme里的获取cookies方法似乎过旧

### ISSUE THREAD

**Issue by NorthNanmu** [metowolf/BilibiliHelper#10]
在某些状态下
`live_h5_player?optype= `并不会发送cookies，而是会发送set-cookies，是否应当改为你博客中的：
> # 更可靠的获取 cookie 方法：
> 需要点开一个直播间，按 F12 选 Network 选项卡，稍等大约 5 分钟后拿到 https://api.live.bilibili.com/eventRoom/ 类似的数据包，复制里面的 cookie 即可。

这一步走了不少弯路xd

**Comment by metowolf** [comment]
README 里的是旧的方法，博客已经做过更新。
感谢提醒喵 ٩(ˊᗜˋ*)و
