### ISSUE TITLE
亲密度不在增加

### ISSUE THREAD

**Issue by Lanceir** [metowolf/BilibiliHelper#106]
2020.5，B站改了大航海抽奖送亲密度的奖励了，只送辣条了。![](http://tiebapic.baidu.com/forum/w%3D580/sign=4fcdee604cb5c9ea62f303ebe538b622/bfedb82bc65c1038281516a9a5119313b17e89b5.jpg)
，粉丝勋章升级漫漫无期。

**Comment by 493Arceus** [comment]
投喂辣条还是可以加亲密度的

**Comment by Lanceir** [comment]
嗯，B站不允许白嫖用户升级太快（笑）
