### ISSUE TITLE
无法登陆，配置文件账号密码确认正确

### ISSUE THREAD

**Issue by 493Arceus** [metowolf/BilibiliHelper#108]
INFO 正在尝试使用用户名、密码登录
POST https://passport.bilibili.com/api/v3/oauth2/login
{"ts":1594980300,"code":-629,"message":"账号或者密码错误"}

**Comment by isXiaoLin** [comment]
从返回来看应该确实是用户名或密码错误，应该是使用了系统用户名，可以尝试使用 `BILI_USERNAME` 代替

**Comment by LynMoe** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
