### ISSUE TITLE
关于cookie不完整

### ISSUE THREAD

**Issue by ZBrettonYe** [metowolf/BilibiliHelper#11]
我给10来个人 免费代挂；为什么有些人的cookies会提示这个？
[警告] cookie 不完整，部分功能已经禁用；
为什么不完整？禁用了什么？ 什么情况下会出现这个？有人能帮助一下吗？

**Comment by metowolf** [comment]
禁用了收发礼物部分，因为 API 要求需要 csrf_token 部分。
这个可能是因为对方的 cookie 没有完整获取。
