### ISSUE TITLE
貌似炸了以后，cookie有问题

### ISSUE THREAD

**Issue by cnkeen** [metowolf/BilibiliHelper#13]
炸了以后，我重新获取cookie, 用HTML5播放器，五分钟后，获取https://api.live.bilibili.com/eventRoom/ 类似的数据包，复制里面的 cookie ，，，然后在shell 用php index.php  无论怎样的cookie都显示了cookie不完整，部分功能会禁用？

**Comment by metowolf** [comment]
需要先更新一下 Bilibili.php 类，cookie 的格式有一些变化
