### ISSUE TITLE
PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by kawowa** [metowolf/BilibiliHelper#16]
PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /home/gitclone/BilibiliHelper/BilibiliHelper/Bilibili.php on line 20

`public $break = 24*60*60;`
这行报错了？？？

？？？？？？

**Comment by kawowa** [comment]
我把它换成246060之后就没问题了，php盲，是运算符的问题吗

**Comment by metowolf** [comment]
可能你的php版本较低

**Comment by kawowa** [comment]
$ php --version
PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
