### ISSUE TITLE
看到介绍上有说抽小电视功能，大概什么时候可以实现呢？

### ISSUE THREAD

**Issue by alhricke** [metowolf/BilibiliHelper#18]
RT，看到介绍上有说抽小电视功能，大概什么时候可以实现呢？虽然可以自动领取宝箱已经很不错了，但是果然还是有自动抽小电视功能更好啊

**Comment by lyt8384** [comment]
估计很难了。。看了下抽电视是用的WebSocket实现的。。。

**Comment by alhricke** [comment]
@lyt8384 我看到网上有些代挂B站直播的一些代挂网，里面有支持宝箱，还有自动领取小电视，和完成每日任务之类的，不知道他们是怎么实现的

**Comment by lyt8384** [comment]
应该是Nodejs模拟操作的。万能的phantomjs。。不过那样风格和占用内存完全不在一个层面了。。哈哈。看作者怎么去实现了

**Comment by czp3009** [comment]
@alhricke 宝箱任务是一个 Restful API,每日任务我还没搞清是什么东西(不是经常上 B站), 不过 API 大致上好像也是一个 Restful API.

领取小电视必须要用 socket. 因为小电视的消息通知是在直播的 弹幕推送 socket 中发送给客户端的, 必须判断数据包里面的 JSON 的 cmd 字段的值来判断数据包类型, 根据不同数据包提取数据. 其中一种 SYS_MSG 会包含小电视的通知. 把里面的 url 字段读取出来, 得到房间号, 再调用另一个 Restful API 去查询该房间的小电视, 得到小电视编号, 用这个编号参与抽奖.

因为这个项目是用 PHP 写的, 所以要用 PHP 实现 socket.

这个项目的一个 fork 项目实现了它, 详见 https://github.com/lkeme/BiliHelper

**Comment by metowolf** [comment]
@czp3009 好耶，很棒的分支，欢迎大佬提交 PR

**Comment by czp3009** [comment]
@metowolf 那个项目不是我写的 =.=

**Comment by soulzzz** [comment]
隔壁Bilihelper更了抽小电视功能 然后一周不到就凉了 封了一批号

**Comment by metowolf** [comment]
B 站最近一直在严打小电视外挂

**Comment by lyt8384** [comment]
是根据频率、一些动态的东西加载。所以建议还是补上去这个功能。设置为默认关闭。频次可自己设定。由使用者决定用不用比较好。

**Comment by metowolf** [comment]
Done. https://github.com/metowolf/BilibiliHelper/commit/cffd8475fe0489b5024977a39301f79ca3cbf225
