### ISSUE TITLE
Try SimpleFramework

### ISSUE THREAD

**Issue by PeratX** [metowolf/BilibiliHelper#2]
[SimpleFramework](https://github.com/iTXTech/SimpleFramework) 是一个PHP CLI框架。

* 多线程支持（可以写成支持同时挂多个账号）
* 命令支持（用于分配任务）
* 彩色输出支持，日志文件支持

如果给您带来困扰（不便），请忽略并close此issue。

**Comment by metowolf** [comment]
非常感谢，看来我重复造了轮子 :+1:
