### ISSUE TITLE
大佬 看看出现这个是什么原因

### ISSUE THREAD

**Issue by wehaha** [metowolf/BilibiliHelper#20]
PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /root/bzhan/BilibiliHelper/Bilibili.php on line 20

**Comment by metowolf** [comment]
直接删除该行即可

**Comment by lyt8384** [comment]
PHP版本问题。。用5.6就可以了。。早期版本定义变量不支持运算。。
