### ISSUE TITLE
现在似乎只抓不到live.bilibili.com的包了

### ISSUE THREAD

**Issue by ZeusGamingPlay** [metowolf/BilibiliHelper#22]
强制使用H5播放器以后抓到的都是
https://data.bilibili.com/log/web?0005161518931203651page|1.2.7-1|346|23058|false|5tbkhCr4-S1Ri-4njQ-RMW3-zbZryp7jWEBF|0|0|https://bvc.live-play.acgvideo.com/live-bvc/936765/live_11153765_9369560_1500.flv?wsSecret=2fd7a2b943f2abc9a098663461c793b8&wsTime=1518932639|138|0
这种地址的。
心跳包则是这种地址的http://api.live.bilibili.com/feed/v1/feed/heartBeat?_cb=jsonp_c8c5377c45a240
依然可用，但是最好改下配置指南吧不然容易造成误导？

**Comment by ZeusGamingPlay** [comment]
以及每个月要更新一次Cookie...感觉不是很方便
提醒一下Dalao你的程序可能被一些淘宝商家用于有偿代挂了？

**Comment by metowolf** [comment]
有偿代挂这个问题之前其实就有人反馈了，个人并不理会这种行为，我也很无奈 X。  
至于心跳包的地址问题，可能配置指南比较老了，多谢提醒。

**Comment by crazymingming** [comment]
测试了下还是可以抓的，随便开个直播间打开f12 ，点network ，然后都会有个叫header的，点过去，然后下拉找到Request Headers，那个内的cookie 就可以使用的 试试看吧

**Comment by czp3009** [comment]
@ZeusGamingPlay 
关于 cookie 更新的问题, B站 的 cookie 跟 token(用于移动客户端) 一样, 过期时间为一个月(服务端上过期). 但是 token 有一个 refreshToken 操作(OAuth2 中的 refreshToken EndPoint), 所以可以用定时任务, 在第 29 天自动刷新 token. token 可以通过 SSO API(OAuth2 中的 SSO) 来转换为 cookie, 所以第 29 天就可以自动更新 cookie 了.

客户端使用的 API 跟 Web 是不一样的, 客户端中 Passport 有关的 API 可以看一下我的 [一篇博文](https://www.hiczp.com/post-145.html)

我正在用 Java 实现 B站 的各种 API, 具体算法可以参考[我的项目](https://github.com/czp3009/bilibili-api).

**Comment by alhricke** [comment]
emmmmmm，现在已经取消挂机获取经验的方式了，只能送礼物了……除非是姥爷
