### ISSUE TITLE
瓜子领取失败

### ISSUE THREAD

**Issue by jitingcn** [metowolf/BilibiliHelper#23]
错误信息: 
```
PHP Warning:  imagecreatefromstring(): Data is not in a recognized format in /root/BiliHelper/includes/Bilibili.php on line 313
PHP Warning:  imagesx() expects parameter 1 to be resource, boolean given in /root/BiliHelper/includes/Bilibili.php on line 314
PHP Warning:  imagesy() expects parameter 1 to be resource, boolean given in /root/BiliHelper/includes/Bilibili.php on line 315
````

初步分析是由于B站修改了captcha获取地址和验证码样式?

目前地址为: `https://api.live.bilibili.com/lottery/v1/SilverBox/getCaptcha?ts=`
getAward: `https://api.live.bilibili.com/lottery/v1/SilverBox/getAward?time_start=%s&time_end=%s&captcha=%s`
getCurrentTask: `https://api.live.bilibili.com/lottery/v1/SilverBox/getCurrentTask`

我也不确定是不是这个问题.......另外ocr模型可能需要重新训练?

**Comment by metowolf** [comment]
感谢反馈，下个版本会做优化
