### ISSUE TITLE
没学过php，请问这样监控cookie失效可以吗?

### ISSUE THREAD

**Issue by sweetasaki** [metowolf/BilibiliHelper#24]
$api->callback = function () {
        //递归调用
        global $account;
        $login = new BiliLogin($account);
        $data = $login->start();
        $cookie = file_get_contents($data['cookie']);
        unlink($data['cookie']);
        //unlink('./tmp/memory.log');
        call_user_func('start', $account, $cookie, $data);
`	**echo file_get_contents('https://sc.ftqq.com/[SCKEY(登入后可见)].send?text='.urlencode('主人服务器又挂掉啦~'));**`
    };

我试过改密码来使cookie失效，可是好像没有任何效果，甚至cookie都没有失效，脚本照样在跑

**Comment by metowolf** [comment]
修改密码不会使 cookie 失效，你可以试试注销操作
另外，监控代码还是得写在 callback 中才有效
