### ISSUE TITLE
PHP运行报错

### ISSUE THREAD

**Issue by MarkDeia** [metowolf/BilibiliHelper#25]
PHP Fatal error:  Uncaught Error: Class 'Bilibili' not found in /root/bl/index.php:6
Stack trace:
#0 {main}
  thrown in /root/bl/index.php on line 6

**Comment by metowolf** [comment]
Bilibili.php 是否下载了

**Comment by MarkDeia** [comment]
肯定下载了。

我猜是因为昨天bilibili live room更新的缘故，现在已经无法像以前那样抓取cookies了，
没有心跳包了。
