### ISSUE TITLE
话说老出现 something wrong! 是什么情况

### ISSUE THREAD

**Issue by crazymingming** [metowolf/BilibiliHelper#26]
[2018-04-14 12:40:20] [签到] OK
[2018-04-14 12:40:20] [签到]
something wrong!

这是log 然后进程就没了 用的是nohup

**Comment by metowolf** [comment]
如果不使用 nohup 直接运行会不会断呢

**Comment by crazymingming** [comment]
已经解决了，感谢大佬的回复。初步判断是宝塔面板的php 守护导致的进程被击杀（
