### ISSUE TITLE
Something garbled.

### ISSUE THREAD

**Issue by XiaoLin0815** [metowolf/BilibiliHelper#3]
这个程序肯定得放到screen里运行，然而放进去以后就变成这样了：
![safd](https://yun.file.xiaolin.in/o_1bm0qighu1m5o151f1u3np96bpma.png)
很明显是乱码的
虽然说不影响使用但强迫症还是有些不舒服的( ･´ω`･ )

Ps.直接运行就正常

**Comment by metowolf** [comment]
其实不需要，你这样 24 小时后还是得再运行一次，最好是直接放在 crontab 里，每天执行一次
关于乱码的问题，可以带上 `-U` 即 `screen -U -S new_screen_name`

**Comment by XiaoLin0815** [comment]
哦吼
对linux不怎么熟悉帮我看看这样写得对不对呗
![dgfdfgdfsg](https://yun.file.xiaolin.in/o_1bm0r4far4ml1l2235r1vfv15bja.png)
但是如果用这种方式岂不是看不到输出？

**Comment by metowolf** [comment]
少写了个重定向 `>` 符号 `php [path]/index.php > [path]/log.txt`
输出可以直接 `cat log.txt` 查看

**Comment by XiaoLin0815** [comment]
好的，THX(｡･ω･｡)

**Comment by XiaoLin0815** [comment]
好的
