### ISSUE TITLE
composer.lock建议加下.gitignore

### ISSUE THREAD

**Issue by lyt8384** [metowolf/BilibiliHelper#35]
composer.lock建议加下.gitignore，不然更新的时候会冲突

**Comment by metowolf** [comment]
感谢提醒，这里是基于以下考虑。

应用类把 composer.lock 文件加入版本控制，保证开发人员、用户安装后的环境是一样的。

而用于别人依赖使用的工具类、库，不把 composer.lock 加入版本控制，因为很容易与其它包的依赖版本造成冲突。

因此部署的时候只需要 `composer install` 就行了，不需要 `update` 操作，也就没有冲突问题了

**Comment by lyt8384** [comment]
理解~~是我习惯性ins后up导致的。
还有config.old也同理，不过不影响使用
