### ISSUE TITLE
0.9.0的在win下的一些BUG

### ISSUE THREAD

**Issue by lyt8384** [metowolf/BilibiliHelper#36]
wrench的Socket。`vendor\wrench\wrench\lib\Wrench\Socket\Socket.php`第311:330行用了`unread_bytes`去判断是否读完数据，但是这个值不太可以在cli下使用，[官方说明](http://php.net/manual/zh/function.stream-get-meta-data.php)。导致win下一直报`No accept header receieved on handshake response`，其他环境没实验。。

`src\plugins\Websocket.php`第34行，origin设置错了，不知道有没有影响，抓包应该是`https://live.bilibili.com`

`config`里，`CALLBACK_URL`字段如果不改。或者其他原因导致请求不是200，会打断整体程序的进行，发出一个`PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error:`的错误。这个是`Bilibili.ERROR: 检测到 Cookie 过期`的时候发生的。

**Comment by metowolf** [comment]
感谢指出，后续版本会做修正
