### ISSUE TITLE
[0.9.1] 应援团签到错误

### ISSUE THREAD

**Issue by wuifantech** [metowolf/BilibiliHelper#38]
您好！
这里有一个错误在运行时：
> Log::notice("应援团 {$value['group_name']} 签到成功，增加 {**$de_raw['data']['add_num']**} 点亲密度"); // [查看](https://github.com/metowolf/BilibiliHelper/blob/1bf32a1a574c5cdd5c40a140a5906b24458ec323/src/plugins/Group.php#L82)

我想它有可能是 `$data['data']['add_num']` ？
如果没有问题，麻烦关闭此 Issues。
谢谢！xD

**Comment by metowolf** [comment]
感谢提醒，刚刚部署的时候也发现了这个问题（
