### ISSUE TITLE
检测到小电视为空，放弃抽奖

### ISSUE THREAD

**Issue by shinBZ** [metowolf/BilibiliHelper#41]
这是怎么回事，基本上在挂超过5个小时经常出现，重新运行后没事，再时间一长就又出现了。

**Comment by shinBZ** [comment]
我看见更新了，问题解决了吗

**Comment by metowolf** [comment]
还没定位到问题所在，GUI 版会直接解决

**Comment by lyt8384** [comment]
建议每个一段时间断开下WebSocket。重建下

**Comment by wuifantech** [comment]
@lyt8384 在我这里并不存在超过一定时间才出现问题的情况，我没有检查程序，但我在多个系统、环境进行了测试，发现在我这里列表为空的情况频率很高，并且是随机出现的（在一开始就有），因此我推测与运行时间无关。

另外我发现挂着程序的时候，在手机端抽小电视有几率出现ID为空的情况，检查程序日志也显示列表为空。
;p

**Comment by lyt8384** [comment]
@wuifantech 我这边其实一开始也有，后来把代码里的随机延时去掉了，然后改监听稍微热门点的房间，就少了很多(每20个中1~2个)，不过挂机超过一定时间依旧会有大量的(3小时左右就开始达到50%+空)。
不过从WebSocket工作原理上来猜测，集群一定会存在资源不均和广播延时的问题，还是建议作者定时重连下比较好。

**Comment by lyt8384** [comment]
我发现个有意思的地方，可能是问题所在，代码我这样改了下，方便调试：

![image](https://user-images.githubusercontent.com/3069157/40219656-ec0a071a-5aa8-11e8-8b5a-95d1c85573d2.png)

然后发现：

![image](https://user-images.githubusercontent.com/3069157/40219691-167b571a-5aa9-11e8-9d28-e2005c94c9e7.png)

每次接收完之后，还有信息在的，没被接收完

**Comment by metowolf** [comment]
@lyt8384 感谢分析，我这里再测试一下
