### ISSUE TITLE
v 0.9.1 大部分功能已失效

### ISSUE THREAD

**Issue by ZeusGamingPlay** [metowolf/BilibiliHelper#43]
如题，脚本会定时挂掉，Debug输出如下：
#0 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28):  in /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

以及B站目前上线了小电视蜜罐，会发送假包，已出现挂脚本的账号被临时封禁的情况！

**Comment by shinBZ** [comment]
这是不打算更新了吗？

**Comment by metowolf** [comment]
由于特殊原因，小电视功能不再继续跟进，其他功能会保持更新
