### ISSUE TITLE
crontab似乎并不能保持index.php一直运行...

### ISSUE THREAD

**Issue by ZeusGamingPlay** [metowolf/BilibiliHelper#5]
我测试发现如果要保持Pulse持续发送，采用screen挂上好像才行，不然直播间经验不会累积？

**Comment by ZeusGamingPlay** [comment]
目前Cookie获取方式有所变更，已经没有https://api.live.bilibili.com/eventRoom/的Header了，统一改成了https://data.bilibili.com/xxxx/xxxxx 但Cookie仍是buvid2=开头的

**Comment by Anapopo** [comment]
try command `cat path/to/your/log.txt`

**Comment by ZeusGamingPlay** [comment]
@Anapopo Hmm....反而让我发现了似乎目前live.bilibili.com的Cookie有效期只有12个小时，每天都需要手动更换......

**Comment by Anapopo** [comment]
@ZeusGamingPlay  I have used my cookie for almost 20 days...

**Comment by metowolf** [comment]
@ZeusGamingPlay 可以尝试从主站登录，然后再进入直播站获取 cookie

**Comment by ZeusGamingPlay** [comment]
@metowolf 我现在的Cookie是在Chrome隐身模式下直接访问live.bilibili.com 得到的，等我尝试一下给你反馈。

**Comment by sola97** [comment]
为啥我隐身模式下得到的cookie关闭浏览器就掉线了，非隐身模式的cookie坚持了24小时多一点也掉线了

**Comment by ZeusGamingPlay** [comment]
@sola97 确实有这样的问题，抓取的Cookie有效期都很短，但是跟Set Cookie一项中给出的Expire Time并不符。

**Comment by ZeusGamingPlay** [comment]
@metowolf 并不行。。。在隐身模式下通过www.bilibili.com登陆，再跳转至live.bilibili.com获取的Cookie依然只能保持12小时的有效时间...

**Comment by ZeusGamingPlay** [comment]
@metowolf 问题找到了。。。我强制把Chrome的Flash播放器打开导致页面没有调用HTML5播放器，然后获取不到live_h5打头的数据包，从Flash播放器里获取的Cookie有效时间不会超过一天 orz...

**Comment by metowolf** [comment]
@ZeusGamingPlay 没想到是 Flash 的问题，感谢提供信息
