### ISSUE TITLE
如何关闭银瓜子兑换功能

### ISSUE THREAD

**Issue by huermos** [metowolf/BilibiliHelper#53]
0.10.1版本docker如何选择关闭银瓜子兑换功能

**Comment by metowolf** [comment]
目前可以先删除 `index.js` 中的入口
https://github.com/metowolf/BilibiliHelper/blob/master/index.js#L33

然后重新构建镜像
```
docker build -t metowolf/bilibilihelper .
```

接下来部署都是一样的了
```
docker run ......
```

后续版本会增加一些功能开关，到时可以通过修改 .env 来关闭和开启功能。

**Comment by huermos** [comment]
了解，十分感谢
直接构建上个commit好像也可阔以

**Comment by metowolf** [comment]
新版可以添加 `-e DISABLE_SILVER2CION=true` 来关闭银瓜子兑换功能
