### ISSUE TITLE
新用户登录问题

### ISSUE THREAD

**Issue by WindJ0Y** [metowolf/BilibiliHelper#56]
新用户登录时
auth.js(27) 使用了config.get('username')作为用户名登录
然而我这里config.get('username')取到的是用户昵称
在这个接口（https://passport.bilibili.com/api/v3/oauth2/login）用昵称密码登录失败
我手动把username改成手机号后登录正常

不知道是不是我账号的问题(=・ω・=)

**Comment by metowolf** [comment]
这里的 username 指的是用户名，可以是手机号也可以是邮箱

**Comment by WindJ0Y** [comment]
> 这里的 username 指的是用户名，可以是手机号也可以是邮箱

我这里config.get('username')的结果好像是个静态的。。我换了个号还是没变
而且不是邮箱，也不是手机号，也不是昵称，而是字符串“WindJ0Y”（每个号都这样）
我开始怀疑是我环境的问题了。。
话说这个支持windows吧。。？

**Comment by metowolf** [comment]
Windows 下可能存在路径问题，具体没做测试，可以考虑直接跑 Docker

**Comment by WindJ0Y** [comment]
> Windows 下可能存在路径问题，具体没做测试，可以考虑直接跑 Docker

好滴，刚刚我换了台电脑测试了下，发现windows下config.get('username')返回的是当前系统账号名23333
