### ISSUE TITLE
怎么关闭扭蛋功能，上次使用PHP版本的会自动消耗扭蛋币

### ISSUE THREAD

**Issue by Yakumo-Yukari** [metowolf/BilibiliHelper#59]
这个版本也会自动消耗扭蛋币吗  如果有请问怎么关闭

**Comment by metowolf** [comment]
目前有两种方式：

 1. Node.js 启动，在 `.env` 中添加 `DISABLE_CAPSULE=true`
 2. Docker 启动，设置环境变量 `-e 'DISABLE_CAPSULE=true'`
