### ISSUE TITLE
学习了原来还可以这样来手动OCR

### ISSUE THREAD

**Issue by zzliux** [metowolf/BilibiliHelper#6]
https://github.com/metowolf/BilibiliHelper/blob/1fcaa3d3cd0f0e4c4ba51d6178b24fb462c1f4b8/Bilibili.php#L217-L234

其中line 227的`similar_text($str,$vo,$per)`真心精妙

整个识别流程差不多已经明白了，vis[]连续为1用来标识每个字符占位宽度，这点做法也非常精妙

不过这种识别方法大概也只能在这种简单的识别中起到作用吧

想起以前看到的google的验证码，人眼看很简单，但是OCR识别难度大大提高，原因就在于验证码中字符的边缘是连接的，这大概也就是OCR中相邻字符的分隔判断的常用方法吧。

总之！收获很大！

**Comment by metowolf** [comment]
同色相连这种识别难度最大，事实上大部分验证码都能通过分离+机器学习来达到高识别率。
至于 B 站这个太过标准了，随便写都能 99.99%
