### ISSUE TITLE
CentOS7 Docker18.09.6运行 报 WARNING 【2434370】 undefined

### ISSUE THREAD

**Issue by liudengxing** [metowolf/BilibiliHelper#63]
其他功能都正常
但会报 warning [roomid] undefined
请问是什么问题？

**Comment by liudengxing** [comment]
报错信息的位置在之前是舰长领取的信息

**Comment by LoliLin** [comment]
大概是没有更新配置文件导致获取房间号失败

**Comment by bilibili-77** [comment]
登录失败 用户名一直是coding 密码正常

**Comment by bilibili-77** [comment]
登录失败 用户名一直是coding

**Comment by liudengxing** [comment]
我重新试了两个环境CentOS + 群晖 Docker环境，也都按照Docker搭建指南搭建，都是报一样的undefined

在 2019-05-25 15:26:57，"XiaoLin" <notifications@github.com> 写道：


大概是没有更新配置文件导致获取房间号失败

**Comment by metowolf** [comment]
可以升级到 metowolf/bilibilihelper:0.10.2 镜像

**Comment by liudengxing** [comment]
DEBUG guard：非特定时间跳过领取
出现这个提示是？

**Comment by metowolf** [comment]
为了避免不间断领取导致帐号被拉黑的机制，只在部分活跃时段进行领取
