### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by bilibili-77** [metowolf/BilibiliHelper#64]
auth.js 登录失败 用户名一直是 coding

**Comment by metowolf** [comment]
注意检查环境变量 USERNAME 是否正确

**Comment by bilibili-77** [comment]
这个怎么看啊

**Comment by bilibili-77** [comment]
> 注意检查环境变量USERNAME是否正确

是liunx的环境变量还是node。js的环境变量啊？

**Comment by metowolf** [comment]
Node.js 运行时的环境变量，具体在 .env 文件中设置

**Comment by bilibili-77** [comment]
> Node.js运行时的环境变量，具体在.env文件中设置

.evn中已经设置好了用户名和密码 密码可以正常使用 用户名会变成coding 我现在的linux 环境用export查看是这个样子

EDITOR=vim
HOME=/home/coding
HOSTNAME=coding.ide
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R
LOGNAME=coding
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
MAIL=/var/mail/coding
PAGER=less
PATH=/home/coding/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/bin/node
PROMPT_EOL_MARK=''
PWD=/home/coding/workspace
SHELL=/usr/bin/zsh
SHLVL=1
SUDO_COMMAND='/bin/bash -c PROMPT_EOL_MARK='\'\'' TTY_ENV=production TTY_PORT=65210 exec /opt/node-v5.6.0/bin/node /usr/local/lib/tty/lib/main.js'
SUDO_GID=0
SUDO_UID=0
SUDO_USER=root
TERM=xterm
TTY_ENV=production
TTY_PORT=65210
USER=coding
VISUAL=vim
ZSH=/home/coding/.oh-my-zsh

**Comment by lovezm** [comment]
舰长亲密度好像不更新了

**Comment by bilibili-77** [comment]
> 舰长亲密度好像不更新了

请不要在我的问题下讨论其他问题

**Comment by metowolf** [comment]
看起来 USERNAME 变成你的系统用户名去了，可以留意一下启动时候打印的配置信息 json 是否正确。
脚本是通过 `process.env.USERNAME` 来获取环境变量的。

**Comment by bilibili-77** [comment]
export USERNAME=我B站的账号
export查看后
export USERNAME=coding 
我已经打算放弃了 55555 我不能自定义环境变量
期待以后你的脚本用process.env.BILIBILI_USER_NAME
我的Linux我并不是很了解 很多系统关键的东西我无法修改 
如果几天后在没有其他人补充回复 到时候再关闭问题吧

**Comment by bilibili-77** [comment]
> 看起来 USERNAME 变成你的系统用户名去了，可以留意一下启动时候打印的配置信息 json 是否正确。  脚本是通过  来获取环境变量的。process.env.USERNAME

export USERNAME=我B站的账号
export查看后
export USERNAME=coding 
(如果是export NODE_ENV=production就不会出现这种问题)
我已经打算放弃了 55555 我不能自定义USERNAME的变量值
期待以后你的脚本用process.env.BILIBILI_USER_NAME
我的Linux我并不是很了解 很多系统关键的东西我无法修改 
如果几天后在没有其他人补充回复 到时候我会关闭问题

**Comment by metowolf** [comment]
建议使用 Docker 部署避免这些问题

**Comment by bilibili-77** [comment]
> 建议使用 Docker 部署避免这些问题

执行curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
提示如下
# Executing docker install script, commit: 2f4ae48
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sudo -E sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker coding

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.

执行sudo usermod -aG docker coding后reset还是会出现此提示

**Comment by bilibili-77** [comment]
> 建议使用 Docker 部署避免这些问题

Docker需要将我的coding用户添加到Docker组 但是我这里环境添加不进去

**Comment by metowolf** [comment]
手动修改目录下的 `.config` 中的用户名

**Comment by bilibili-77** [comment]
> 手动修改目录下的 .config 中的用户名

试过了 好像不行 一会我在试试

**Comment by bilibili-77** [comment]
> 手动修改目录下的 .config 中的用户名

这次可以了 原来的nvm环境配置的有问题 加上了如下内容

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

不过用户名还是coding  然后手动修改了.config中的用户名 登录成功 不知道上次修改.config不成功的原因跟nvm有没有关系
