### ISSUE TITLE
舰长亲密度好像又不更新了诶

### ISSUE THREAD

**Issue by lovezm** [metowolf/BilibiliHelper#65]
舰长亲密度好像又不更新了诶

**Comment by metowolf** [comment]
近期由于 B 站关闭直播弹幕，所以上游 API 也无法获得新的舰长名单

**Comment by lovezm** [comment]
难怪=。= 还有顺便问一下 由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝  这个是啥东西
