### ISSUE TITLE
依旧是Cookie失效的问题......

### ISSUE THREAD

**Issue by ZeusGamingPlay** [metowolf/BilibiliHelper#7]
每24小时就要去手动更新一次Cookie，无论是隐身模式下访问还是普通模式下访问都一样，已确认开启了B站HTML播放器。
另外我个人有个疑惑，安装说明称使用crontab在00:03定时执行index.php并把日志存入log.txt下，经我测试执行后日志只显示了签到成功、领取签到奖励成功，但并没有显示向B站服务器发送心跳包；之后采用screen运行index.php日志中才开始显示心跳包发送并累计经验.......
注：测试环境 centos 7.2 Final & PHP 5.6

**Comment by ZeusGamingPlay** [comment]
同时，被挂入脚本的账号不能在网页浏览器执行登入或登出操作，一样会使Cookie失效（在隐身模式挂入的也不例外）

**Comment by mixool** [comment]
Debian 8 开始也是24小时需要更新cookies，后来不知咋的获取到的cookie就可以用了一个月了。怀疑你获取cookie姿势不对。

**Comment by ZeusGamingPlay** [comment]
@mixool 不会啊。。。隐身模式访问F12获取的。。。

**Comment by cnkeen** [comment]
试下隐身模式，登录的时候，（记住登录），再用HTML5播放器，五分钟后，获取https://api.live.bilibili.com/eventRoom/ 类似的数据包，复制里面的 cookie 试试？
