### ISSUE TITLE
你好，现在已经无法登陆使用了，可能使用了新的验证码

### ISSUE THREAD

**Issue by jn32707** [metowolf/BilibiliHelper#78]
INFO 检查 Token 是否过期
WARNING 检测到 Token 需要更新
INFO 正在刷新 Token
INFO 正在获取公钥
NOTICE 公钥获取成功
INFO 正在尝试使用用户名、密码登录
ERROR 登录失败

**Comment by LoliLin** [comment]
应该已经在 #77 修复了(
拉取一遍新版试试看?

**Comment by jn32707** [comment]
已修改成
        # iOS 6680
        // $appkey = '27eb53fc9058f8c3';
        // $appsecret = 'c2ed53a74eeefe3cf99fbd01d8c9c375';
        # Android
        // $appkey = '1d8b6e7d45233436';
        // $appsecret = '560c52ccd288fed045859ed18bffd973';
        # 云视听 TV
        $appkey = '4409e2ce8ffd12b8';
        $appsecret = '59b43e04ad6965f34319062b478f83dd';

问题依旧

**Comment by GFwer** [comment]
node 版根据 PR 替换`appkey`和`appsecret`是可以的

**Comment by LoliLin** [comment]
确认现 API 接口需要验证码..
准备更换新的 API 接口 (@metowolf
