### ISSUE TITLE
请问一下我该如何获取到.env文件中需要的参数

### ISSUE THREAD

**Issue by StubbornYang** [metowolf/BilibiliHelper#80]
您好！第一次使用，想请问一下我该如何获取到.env文件中需要的这两个参数
ACCESS_TOKEN=
REFRESH_TOKEN=

【参数为空时的log如下：】
Weirdo@WeirdodeMacBook-Pro ~ % docker logs --tail 30 -f bilibili
ERROR 登录失败
INFO 检查每日任务
GET https://api.live.bilibili.com/i/api/taskInfo
{"code":1,"msg":"invalid params","message":"invalid params","data":[]}

**Comment by jn32707** [comment]
我刚部署也遇到，原因是AppKey AppSecret过期导致登陆失败
ACCESS_TOKEN =
REFRESH_TOKEN =
这两个不需要填，更新容器里 “/utils/sign.js“ 这个文件 AppKey 以及 AppSecret即可
https://github.com/metowolf/BilibiliHelper/pull/79/commits/aa7a07a1addd1991e56c6a140259038786463b39

**Comment by StubbornYang** [comment]
请教一下该如何更新容器里 “/utils/sign.js“ 这个文件 及如何获取AppKey 以及 AppSecret

**Comment by LoliLin** [comment]
已在 #79 中修复，直接拉取最新版程序在本地构建即可
