### ISSUE TITLE
请问遇到验证码错误时需要怎么处理

### ISSUE THREAD

**Issue by cace2008** [metowolf/BilibiliHelper#82]
请问遇到验证码错误提示时需要怎么处理
NOTICE 公钥获取成功
INFO 正在尝试使用用户名、密码登录
POST https://passport.bilibili.com/api/v3/oauth2/login
{"ts":·······························845"},"message":"验证码错误"}
ERROR 登录失败

怎么做才能正常登入呢

**Comment by LoliLin** [comment]
参照 #78
