### ISSUE TITLE
云服务器liunx无法获取房间id 现实房间不存在

### ISSUE THREAD

**Issue by ZeroReimu** [metowolf/BilibiliHelper#84]
GET https://api.live.bilibili.com/room/v1/Room/room_init?id=undefined
{"code":60004,"msg":"直播间不存在","message":"直播间不存在","data":[]}
WARNING guard: 获取房间信息失败

有什么解决办法吗

**Comment by LoliLin** [comment]
请提供一下运行环境及环境变量传递方式

**Comment by DeonCao** [comment]
我这里也是一样，更新了容器后就提示这个了。
运行环境啊 
MacOS 10.15.3
Docker 2.2.0.3
BilibiliHelper 最新
.env  配置启动的
`DEBUG guard：概率性跳过领取
GET https://api.live.bilibili.com/room/v1/Room/room_init?id=undefined
{"code":60004,"msg":"直播间不存在","message":"直播间不存在","data":[]}
WARNING guard: 获取房间信息失败`
配置文件中修改了 用户名，密码，以及房间ID三项。

**Comment by gtbl2012** [comment]
这个问题应该在PR#85修复了，拉一下新的代码试试？

**Comment by BBBBchan** [comment]
同样有这个问题，使用Docker拉取的最新代码。
``` 
WARNING guard: 获取房间信息失败
GET https://api.live.bilibili.com/room/v1/Room/room_init?id=undefined
{"code":60004,"msg":"直播间不存在","message":"直播间不存在","data":[]}
```

**Comment by gtbl2012** [comment]
问题已查出，docker hub上新自动构建的版本tag都标为了edge，用户默认拉取latest版本因此未应用PR#85。

**Comment by BBBBchan** [comment]
问题应该出在guard.js下的getGuardList函数，该函数返回值为:
```
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```
但是在同样网络环境下利用其它工具按照User-Agent的构造方法可以得到正确的返回值。

**Comment by LoliLin** [comment]
请拉取 Docker Hub 中构建时间最新的镜像或者执行 `docker pull metowolf/bilibilihelper:edge` 拉取并使用开发版镜像即可
