### ISSUE TITLE
为啥我的username设置了 登陆的时候还是root

### ISSUE THREAD

**Issue by Mr-Fengalang** [metowolf/BilibiliHelper#98]
emmm
 登陆不上去 也不知道怎么获取id  emmm

**Comment by LoliLin** [comment]
被系统的环境变量覆盖了，请使用 Docker 或使用 `USERNAME=username node index.js` 启动程序

**Comment by Mr-Fengalang** [comment]
> 被系统的环境变量覆盖了，请使用 Docker 或使用 `USERNAME=username node index.js` 启动程序

我用docker启动  发现日志登录失败 验证码不正确 怎么能获取accesstoken

**Comment by LoliLin** [comment]
Reference https://github.com/metowolf/BilibiliHelper/issues/95#issuecomment-614435126
