### ISSUE TITLE
关于密码中特殊字符的处理

### ISSUE THREAD

**Issue by hui-shao** [metowolf/BilibiliHelper#99]
我是使用 node.js 部署的
我的密码里面含有一对花括号 {}
在程序读取时无法正常识别花括号，导致无法登陆
（是在编辑 .env 的时候需要转义吗？）
希望能处理下，加强对这类特殊字符的支持，谢谢你的付出

**Comment by hui-shao** [comment]
哦，对了，另外还有 登录时需要验证码的问题
```
POST https://passport.bilibili.com/api/v3/oauth2/login
{"ts":1588485447,"code":-105,"data":{"url":"https://passport.bilibili.com/register/verification.html?success=1&gt=XXXXXXXXXXXXXXXXX&challenge=XXXXXXXXXXXXXXXX&ct=1&hash=XXXXXXXXXXXX"},"message":"验证码错误"}
```

**Comment by LoliLin** [comment]
关于配置文件, 可以参考 https://github.com/motdotla/dotenv#rules

关于登陆需要验证码的问题可以参考 https://github.com/metowolf/BilibiliHelper/issues/95#issuecomment-614435126

**Comment by hui-shao** [comment]
> 关于配置文件, 可以参考 https://github.com/motdotla/dotenv#rules
> 
> 关于登陆需要验证码的问题可以参考 [#95 (comment)](https://github.com/metowolf/BilibiliHelper/issues/95#issuecomment-614435126)

好的，感谢答疑

**Comment by hui-shao** [comment]
你好，我还想咨询一下，使用时是执行一次 `nohup node index.js &` 即可，然后之后每天到点了都会自动运行；
还是需要加入 crontab ，每天都执行一遍  `node index.js ` ?


另外 在 env 中设置了 DEBUG=false 似乎不起作用……

**Comment by LoliLin** [comment]
只需保持程序运行即可, 无需定期执行

至于 DEBUG 关不关无伤大雅, 从代码逻辑来讲这个选项只会影响请求结果是否输出而不会屏蔽 DEBUG 消息

**Comment by LoliLin** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
